version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Installing dependencies"

  pre_build:
    commands:
      - echo "Logging in to Docker Hub"
      - echo "awais1234" | docker login -u "awais1230" --password-stdin
      - echo "Pre-build phase complete"

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Docker images"
      - docker-compose build
      - echo "Build completed"

  post_build:
    commands:
      - echo "Tagging and pushing Docker images to Docker Hub"
      - docker tag nginx:latest awais1230/nginx:newnginxlatest
      - docker tag php:latest awais1230/php:newphplatest
      - docker push awais1230/nginx:newnginxlatest
      - docker push awais1230/php:newphplatest
      - echo "Docker images pushed"

artifacts:
  files:
    - appspec.yml
    - scripts/*
